-- PMDCollab water: the species drawn WHOLE over water (true flyers and floaters).
-- Every other PMD Pokemon on water swims: cut off at its baked waterline with a
-- foam line (lib/pmd_renderer.lua). EDIT BY HAND: add a species with
-- `[dex] = true`, or a form with `["<dex3>-<form>"] = true` (a form key wins over
-- its dex; `false` keeps a form swimming when its base species flies).
-- Seeded by tools/generate_pmd_water.py (re-running it overwrites edits).
return {
  fly = {
    [12] = true, -- Butterfree
    [15] = true, -- Beedrill
    [22] = true, -- Fearow
    [41] = true, -- Zubat
    [42] = true, -- Golbat
    [92] = true, -- Gastly
    [93] = true, -- Haunter
    [109] = true, -- Koffing
    [145] = true, -- Zapdos
    [166] = true, -- Ledian
    [169] = true, -- Crobat
    [187] = true, -- Hoppip
    [189] = true, -- Jumpluff
    [193] = true, -- Yanma
    [200] = true, -- Misdreavus
    [201] = true, -- Unown
    [207] = true, -- Gligar
    [251] = true, -- Celebi
    [269] = true, -- Dustox
    [278] = true, -- Wingull
    [279] = true, -- Pelipper
    [292] = true, -- Shedinja
    [314] = true, -- Illumise
    [330] = true, -- Flygon
    [334] = true, -- Altaria
    [337] = true, -- Lunatone
    [338] = true, -- Solrock
    [343] = true, -- Baltoy
    [344] = true, -- Claydol
    [351] = true, -- Castform
    [353] = true, -- Shuppet
    [355] = true, -- Duskull
    [358] = true, -- Chimecho
    [362] = true, -- Glalie
    [374] = true, -- Beldum
    [380] = true, -- Latias
    [381] = true, -- Latios
    [384] = true, -- Rayquaza
    [385] = true, -- Jirachi
    [414] = true, -- Mothim
    [415] = true, -- Combee
    [416] = true, -- Vespiquen
    [425] = true, -- Drifloon
    [426] = true, -- Drifblim
    [429] = true, -- Mismagius
    [436] = true, -- Bronzor
    [437] = true, -- Bronzong
    [442] = true, -- Spiritomb
    [468] = true, -- Togekiss
    [469] = true, -- Yanmega
    [472] = true, -- Gliscor
    [478] = true, -- Froslass
    [479] = true, -- Rotom
    [480] = true, -- Uxie
    [481] = true, -- Mesprit
    [482] = true, -- Azelf
    [488] = true, -- Cresselia
    [491] = true, -- Darkrai
    [517] = true, -- Munna
    [518] = true, -- Musharna
    [527] = true, -- Woobat
    [528] = true, -- Swoobat
    [561] = true, -- Sigilyph
    [562] = true, -- Yamask
    [577] = true, -- Solosis
    [578] = true, -- Duosion
    [579] = true, -- Reuniclus
    [602] = true, -- Tynamo
    [603] = true, -- Eelektrik
    [605] = true, -- Elgyem
    [608] = true, -- Lampent
    [609] = true, -- Chandelure
    [615] = true, -- Cryogonal
    [641] = true, -- Tornadus
    [663] = true, -- Talonflame
    [666] = true, -- Vivillon
    [679] = true, -- Honedge
    [681] = true, -- Aegislash
    [708] = true, -- Phantump
    [710] = true, -- Pumpkaboo
    [714] = true, -- Noibat
    [715] = true, -- Noivern
    [717] = true, -- Yveltal
    [720] = true, -- Hoopa
    [738] = true, -- Vikavolt
    [742] = true, -- Cutiefly
    [743] = true, -- Ribombee
    [764] = true, -- Comfey
    [785] = true, -- Tapu Koko
    [790] = true, -- Cosmoem
    [792] = true, -- Lunala
    [798] = true, -- Kartana
    [804] = true, -- Naganadel
    [822] = true, -- Corvisquire
    [823] = true, -- Corviknight
    [826] = true, -- Orbeetle
    [829] = true, -- Gossifleur
    [830] = true, -- Eldegoss
    [841] = true, -- Flapple
    [854] = true, -- Sinistea
    [855] = true, -- Polteageist
    [867] = true, -- Runerigus
    [868] = true, -- Milcery
    [873] = true, -- Frosmoth
    [885] = true, -- Dreepy
    [898] = true, -- Calyrex
    [905] = true, -- Enamorus
    [962] = true, -- Bombirdier
    [966] = true, -- Revavroom
    [994] = true, -- Iron Moth
  },
}
