#!/usr/bin/env python3
"""Keeps .modkitignore in step with the repo.

Gen1Recomp's modkit matches .modkitignore entries as EXACT file paths (no
globs, a directory name excludes nothing), so every file that must stay out of
the distributed package has to be listed by name -- and a new test, tool,
script or doc is easy to forget. This tool derives the list from the layout
below and either checks it or rewrites it:

    python3 tools/check_modkitignore.py           # exit 1 when .modkitignore is out of date
    python3 tools/check_modkitignore.py --write   # regenerate .modkitignore

scripts/build-mod.py runs the check first, so a release cannot be built with a
stale list. The package carries only SHIPPED_FILES and SHIPPED_DIRS; everything
else in the repo is excluded. A new top-level file or folder that is in neither
list is an ERROR (not silently shipped, not silently dropped): decide, then add
it to SHIPPED_* here or leave it out (it is excluded by default once you have
looked at it -- add it to EXCLUDED_DIRS / EXCLUDED_FILES).
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# What the mod needs to run, plus the licence / attribution / docs it ships with.
SHIPPED_FILES = {
    "manifest.json", "main.lua", "options.lua",
    "LICENSE", "THIRD_PARTY_NOTICES.md", "README.md", "CHANGELOG.md",
}
SHIPPED_DIRS = {"lib", "assets"}

# Repo-only: listed in .modkitignore file by file, in this order.
EXCLUDED_DIRS = [
    ("# unit tests and engine tests", "tests"),
    ("# bake / validation / asset tools", "tools"),
    ("# build scripts", "scripts"),
    ("# manual test checklist and other docs", "docs"),
]
# local build output (names change with every build, so these go stale harmlessly)
BUILD_DIRS = ["dist", "release"]
# local notes and the README banner image
EXCLUDED_FILES = ["CLAUDE.md", "WoH.png"]

SKIP_DIR_NAMES = {"__pycache__", ".git", ".modkit", ".vscode"}

HEADER = """# Exact relative paths excluded from the distributed package.
# modkit matches literally (no globs, and a directory name excludes nothing:
# every FILE is listed). See Gen1Recomp CONTRIBUTING-mods.md.
#
# GENERATED by tools/check_modkitignore.py -- run `python3 tools/check_modkitignore.py --write`
# after adding a file under tests/, tools/, scripts/ or docs/ (scripts/build-mod.py
# refuses to build while this file is out of date).
#
# The package carries only what the mod needs to run (manifest.json, main.lua,
# options.lua, lib/, assets/) plus LICENSE, THIRD_PARTY_NOTICES.md, README.md
# and CHANGELOG.md. Everything below stays in the repo only.
# scripts/build-mod.py (verify_zip) is the backstop if a path is missing here.
"""


def files_under(directory: str) -> list[str]:
    base = ROOT / directory
    out: list[str] = []
    if not base.is_dir():
        return out
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIR_NAMES and not d.startswith(".")]
        for name in filenames:
            if name.startswith("."):
                continue
            rel = Path(dirpath, name).relative_to(ROOT).as_posix()
            out.append(rel)
    return sorted(out)


def unclassified() -> list[str]:
    """Top-level entries that are neither shipped nor known repo-only."""
    known_dirs = SHIPPED_DIRS | {d for _, d in EXCLUDED_DIRS} | set(BUILD_DIRS)
    known_files = SHIPPED_FILES | set(EXCLUDED_FILES)
    bad = []
    for entry in sorted(os.listdir(ROOT)):
        if entry.startswith(".") or entry in SKIP_DIR_NAMES:
            continue
        p = ROOT / entry
        if p.is_dir():
            if entry not in known_dirs:
                bad.append(entry + "/")
        elif entry not in known_files:
            bad.append(entry)
    return bad


def render() -> str:
    out = HEADER
    for title, directory in EXCLUDED_DIRS:
        out += f"\n{title}\n" + "\n".join(files_under(directory)) + "\n"
    local = [f for f in EXCLUDED_FILES if (ROOT / f).is_file()]
    out += "\n# local notes and the README banner image (not needed to run)\n" + "\n".join(local) + "\n"
    build = [p for d in BUILD_DIRS for p in files_under(d)]
    out += "\n# local build output\n" + "\n".join(build) + "\n"
    return out


def main(argv: list[str]) -> int:
    bad = unclassified()
    if bad:
        print("ERROR: top-level entries that are not classified in tools/check_modkitignore.py:",
              file=sys.stderr)
        for b in bad:
            print(f"  {b}", file=sys.stderr)
        print("Add each to SHIPPED_FILES / SHIPPED_DIRS (it ships) or EXCLUDED_FILES / "
              "EXCLUDED_DIRS (repo only).", file=sys.stderr)
        return 1
    want = render().replace("\n", "\r\n")
    path = ROOT / ".modkitignore"
    have = path.read_bytes().decode("utf-8") if path.is_file() else ""
    if "--write" in argv:
        if have != want:
            path.write_bytes(want.encode("utf-8"))
            print(".modkitignore rewritten")
        else:
            print(".modkitignore already up to date")
        return 0
    listed = {l.strip() for l in have.splitlines() if l.strip() and not l.startswith("#")}
    wanted = {l.strip() for l in want.splitlines() if l.strip() and not l.startswith("#")}
    build = {p for d in BUILD_DIRS for p in files_under(d)}
    # a source file (test / tool / script / doc / local note) that is not listed would
    # ship in a modkit package: that is the error. Build output changes with every
    # build and files that no longer exist are harmless: those are only notes.
    missing = sorted(wanted - listed - build)
    if missing:
        for p in missing:
            print(f"ERROR: .modkitignore is missing: {p}", file=sys.stderr)
        print("Run: python3 tools/check_modkitignore.py --write", file=sys.stderr)
        return 1
    for p in sorted((wanted & build) - listed):
        print(f"note: build output not listed in .modkitignore: {p}")
    for p in sorted(listed - wanted):
        print(f"note: .modkitignore lists a file that no longer exists: {p}")
    print("check_modkitignore: ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
